### ISSUE TITLE
Are batch field resolvers a viable optimization? 

### ISSUE THREAD

**Issue by stephenh** [graphile/crystal#1802]
:wave: I just heard about Grafast from a recent [HN comment](https://news.ycombinator.com/item?id=37814153), about a post talking about the known "graphql.js creates a bunch of promises" perf issue.

It's amazing to see you're working on the problem already. :1st_place_medal: 

Given you've thought a lot about this problem, I'm curious if something as simple as "batch field resolvers" would be a potentially viable optimization approach? (Grafast's plan resolvers certainly seem optimal, but I'm still grokking them...)

For example, the prototypical `User.firstName` field resolver:

```
const userResolver = {
  firstName(user) => user.firstName
}
```

If this was:

```
const userResover = {
  firstName(users) => users.map(u => u.firstName);
}
```

This would cut out a whole swath of promises (if `firstName` was async) by making 1 promise per field, instead instead of 1 promise per field+per entity.

I dunno, is this approach missing something obviously naive? I feel like it probably is, otherwise it seems someone would have tried it already?

Thanks!

**Comment by benjie** [comment]
```ts
const userResolver = {
  firstName: (user) => user.firstName
}
```
^ This resolver does not use any promises, and GraphQL.js will not generate any promises in order to resolve it; so your optimization for _this specific resolver_ is unnecessary.

However, the proliferation of promises in GraphQL.js schemas, particularly ones that use the DataLoader pattern (or GraphQL Shield), is a significant overhead that Gra*fast* helps to avoid. Every "async step" in Gra*fast* works in the way that you describe: a batch function is called passing in the list of values (like DataLoader) and returning a promise to a list of results (or a list of promises, or a promise to a list of promises - it's up to the person implementing the step). For well implemented steps, this typically means that only a handful of promises are used even when evaluating a field from within a list of a list.

But your question was, would having this execution model (like in https://www.npmjs.com/package/graphql-resolve-batch, but with an optimized GraphQL.js implementation that executes these batches directly rather than via traditional resolvers) be sufficient? It would certainly help increase performance a bit by avoiding the unnecessary promises; but I think that this is a minor optimization compared to embracing the declarative nature of GraphQL and _planning_ the request holistically, which can give you order of magnitude efficiency gains.

Essentially the reason you don't see an engine doing as you describe is that the cost of promises isn't enough to justify building an entire new engine just to avoid that one relatively minor issue. GraphQL's resolver-based execution model (even when extended with batching as you describe) doesn't lend itself to optimization because the previous layer has to execute before the next layer is "discovered" - meaning that the previous layer cannot factor "future" layers into its actions (e.g. selecting only the attributes it will need, performing joins, skipping fetching entirely because we only need the `id`, which we already have, etc). This is a real shame given the GraphQL language itself is declarative; and something Gra*fast* sets out to solve (along with all the promise issues and more).

Please consider watching my talk at GraphQLConf a few weeks ago that announced the Gra*fast* project for a full understanding of what I mean:

https://www.youtube.com/watch?v=4ao-zjiOGx8

**Comment by stephenh** [comment]
> This resolver does not use any promises

Yes, sorry; I included a "if firstName was async" disclaimer in my prose, but made the example overly simplified and should have included an `async` keyword.

> graphql-resolve-batch

Interesting! I had not seen that, so thanks for the link...

I got my hopes up, but I think, as you insinuated, it's just another flavor of "batching via promises", so perhaps it is more ergonomic for users to write (than dataloaders), but, right, doesn't really help the runtime # of promises:

https://github.com/calebmer/graphql-resolve-batch/blob/master/src/batch.js#L16

> Essentially the reason you don't see an engine doing as you describe is that the
> cost of promises isn't enough to justify building an entire new engine just to
> avoid that one relatively minor issue.

Fwiw I think the [blog post from the HN link](https://www.softwareatscale.dev/p/the-hidden-performance-cost-of-nodejs) shows otherwise, especially once APM instrumentation is taken into account:

* "We see that wrapping each user and item in a promise causes a 2x or 3x increase in request latency." (without async_hooks)
* "We roughly see that Async Hooks roughly adds a 3 - 3.5x overhead to these resolvers."

This basically matches our internal profiling results, which is that large-ish GQL requests the runtime, imo/afaict, _would_ actually benefit from "collapsing the loops" and removing the "promise per field per entity" overhead.

Obviously it's hard to argue against Grafast doing "even _more_ optimization", but just seems like somewhat low-hanging fruit.

Fwiw/per Grafast, I'm still a little skeptical about users the plan-based resolvers by hand (learning the `$each`/etc. DSL), _but_ I could see tooling/frameworks generate the plan-based resolvers and have that work out really, so I'm excited to try it.

> https://www.youtube.com/watch?v=4ao-zjiOGx8

Thanks! I'll definitely watch it. Out of curiosity, were there any other talks from GraphQLConf you found particularly neat? I would have liked to attend, but great to see the talks online.

**Comment by benjie** [comment]
> Fwiw I think the [blog post from the HN link](https://www.softwareatscale.dev/p/the-hidden-performance-cost-of-nodejs) shows otherwise

Evidenced by there _not being_ an engine that does this I stand by my assertion that the cost of writing the engine has (until now perhaps; see below!) outweighed the savings. The numbers they quote are for schemas doing bad things (e.g. wrapping every resolver in a promise); rather than writing an entire new GraphQL engine I suspect many companies have found it cheaper to just _not do that_ :wink:

Either way, Gra*fast* solves this problem, but that's really a very minor feature of Gra*fast*. I don't think it would be much effort to build the engine you suggest on top of Gra*fast*; effectively it would be just wrapping each of your "batch resolver"s with a [`loadOne`](https://grafast.org/grafast/step-library/standard-steps/loadOne) step and you're about done I think...

Here's what batch resolvers might look like in your suggested system:

```ts
const batchResolvers = {
  Query: {
    async currentUser(_, args, context) {
      const [user] = await getUsers([context.userId]);
      return _.map(() => user);
    }
  },
  User: {
    firstName(users, args) {
      return list.map(user => user.firstName);
    },
    async friends(users, args) {
      const userIds = users.map(u => u.id);
      /** @type {number[][]} */
      const listsOfFriendIds = await getFriendIdsForUserIds(userIds);
      const friends = await getUsers([...new Set(listsOfFriendIds.flat())]);
      return listsOfFriendIds.map(friendIds => friendIds.map(id => friends.find(f => f.id === id)));
    }
  }
}
```

And here's how you might turn them (along with `typeDefs` defining your GraphQL schema via SDL) into a Gra*fast*-powered GraphQL schema without even writing your own step classes:

```ts
import { makeGrafastSchema, context } from "grafast";

function convertBatchResolverToPlan(batchResolver) {
  return ($parent, fieldArgs) => {
    const $args = fieldArgs.getRaw();
    const $context = context();
    return loadOne([$parent, $args, $context], (tuples) => {
      // We know there's only going to be one value for `args` and `context`,
      // so extract them from the first tuple:
      const [, args, context] = tuples[0];
      // Now extract all the parent values:
      const parents = tuples.map((t) => t[0]);
      // And then run this all through the batch resolver
      return batchResolver(parents, args, context);
    });
  };
}

// Convert `{ [typeName]: { [fieldName]: batchResolver } }`
// to      `{ [typeName]: { [fieldName]: planResolver } }`
const plans = Object.fromEntries(
  Object.entries(batchResolvers).map(([typeName, fields]) => [
    typeName,
    Object.fromEntries(
      Object.entries(fields).map(([fieldName, batchResolver]) => [
        fieldName,
        convertBatchResolverToPlan(batchResolver),
      ]),
    ),
  ]),
);

const schema = makeGrafastSchema({ typeDefs, plans });
```

Note: I've not tested this at all (though I have piped it through the Prettier playground for formatting!); and it might have issues with polymorphism and subscriptions, but as a first draft it seems reasonably legit. Remember to credit me if you turn this into The Next Big Thing in GraphQL!

> Fwiw/per Grafast, I'm still a little skeptical about users the plan-based resolvers by hand (learning the $each/etc. DSL), but I could see tooling/frameworks generate the plan-based resolvers and have that work out really, so I'm excited to try it.

I've put a lot of effort into trying to make the DSL pretty close to the code you would write, and the plan diagrams really help with understanding; but there's definitely more to be done to help people grok this. I see them as being somewhat similar to the `useFoo()` hooks in React in terms of learning curve.

> were there any other talks from GraphQLConf you found particularly neat?

I spent the vast majority of the conference talking with attendees so didn't actually see many of the talks! From what I heard though, they were all great. I plan to go through and watch each of them at some point when I have time :sweat_smile:
