### ISSUE TITLE
PgSimplifyInflectionPreset + PostGraphileConnectionFilterPreset = error

### ISSUE THREAD

**Issue by innermatrix** [graphile/crystal#1806]
### Summary

Getting unrecoverable schema error trying to use `PgSimplifyInflectionPreset` and `PostGraphileConnectionFilterPreset` in v5

### Steps to reproduce

```
git clone https://github.com/innermatrix/crystal.git
cd crystal
git checkout 1806-plugin-conflict
yarn install && yarn build && ( cd scripts/sql2gql && env DEBUG=graphile-build:warn POSTGRES_PORT=15432 ./sql2gql.mjs example.sql ./example-preset.mjs example.gql )
[noise]
graphile-build:warn Recoverable error occurred: Error: A naming conflict has occurred - two entities have tried to define the same key 'subscriptionStatus'.
[noise]
AggregateError: Schema construction failed due to 5 validation failure(s). First failure was: Query root type must be provided.
[noise]
```

### Expected results

No error

### Actual results

Error

(See above for error details)

**Comment by benjie** [comment]
Please don't cut "noise" from their error traces. If I really thought that was noise I wouldn't bother adding it to the error messages in the first place! In most cases I can look at error messages and tell you what's gone wrong without having to go through cloning stuff and fiddling with docker.

**Comment by benjie** [comment]
Your schema is:

```
CREATE TABLE subscription_statuses (
    subscription_status text PRIMARY KEY
);

CREATE TABLE member_subscriptions (
    subscription_status text NOT NULL DEFAULT 'ACTIVE'::text REFERENCES subscription_statuses(subscription_status)
);
```

Your database schema is not compatible with the simplify inflection plugin; one of the assumptions of that plugin is that primary keys have a name like `id` (or `pk`, or `uuid`, or ending with `_id` or `Id` or `_pk` or `Pk`, or `_uuid` or `Uuid`) and foreign keys are similarly named (see [this regexp](https://github.com/graphile/crystal/blob/55982ac250a93af3fd0d3eb22a91f8c179bfff03/graphile-build/graphile-simplify-inflection/src/index.ts#L147)). Naming your primary key for the singular of the table and doing the same for foreign keys is going to cause you headaches.

I'll document this expectation.

Incidentally if you use the relay preset, this issue might go away as `member_subscriptions.subscription_status` will no longer be represented as a field directly, instead you'll have to navigate `MemberSubscriptions.subscriptionStatus>subscriptionStatus` to read it.

**Comment by benjie** [comment]
Updated docs: https://github.com/graphile/crystal/pull/1809

**Comment by innermatrix** [comment]
Hmm. I have complicated feelings about this response. 

* I see your point but
* It worked in v4 and it seems like a pretty substantial breaking change (= not easy to revise as part of v5 upgrade) and also
* The problem doesn’t exist if I use only the simplify inflector, but you said that the problem is that the schema is incompatible with the simplify inflector? And finally
* Trying to figure out how to go about upgrading to v5, if I must, would be a lot easier if I got a clearer error message (like “this entity is not compatible with this inflector for this reason”) rather than having to make sense of naming conflicts

That said, I can probably make it work, but it’s also probably at the top of my answer about “what’s a pain about v5” right now

**Comment by benjie** [comment]
> but you said that the problem is that the schema is incompatible with the simplify inflector

I'll admit I have not ran your example (it's 3pm, I'm already exhausted, and I've barely written any actual code today yet despite the [huge amount of work left to do before V5.0.0 can be released](https://github.com/orgs/graphile/projects/3)); I was attempting to extrapolate from the error messages that you truncated and my expectations figuring there was a conflict between the field name `subscription_status` wanting to be called `subscriptionStatus` and the relationship to `subscription_statuses` which would _also_ want to be called `subscriptionStatus`. Maybe I misdiagnosed? It would be easier to tell with the full error trace. Generally I'm pretty good at this extrapolation, just as how yesterday I correctly diagnosed your previous issue even without an accurate reproduction.

> The problem doesn’t exist if I use only the simplify inflector

So it's a bug in the filter plugin? That would make sense; the inflectors for the filter plugin were a bit funky (they re-used the existing inflectors, but with different input parameters) and that had to change in the V5 version. It's also likely that the filter plugin doesn't apply the exact same behavior logic as the rest of the schema. Perhaps you can pin down the specific filter plugin inflector that's giving you issues and replace it?

> It worked in v4 and it seems like a pretty substantial breaking change

You're not using `makeV4Preset` in your reproduction, so you get the V5 default inflection _not_ the V4-like inflection. It's not expected that "amber" preset matches a V4 schema at all. It was also incredibly tough to convert the filter plugin to V5 whilst keeping its various idiosyncrasies; should you wish to extend the "V4 preset" with more inflectors from the filter plugin, that would certainly be helpful for other users of that plugin.

> would be a lot easier if I got a clearer error message (like “this entity is not compatible with this inflector for this reason”) rather than having to make sense of naming conflicts

It sure would! But all of the entities _are_ compatible with the inflectors individually, the problem is that they're all clamouring for the same names. Unfortunately, since I don't see schemas like yours very often, I didn't think to spend the time to write into the program specific detection of that particular pattern and a custom error message. All the system can do is tell you where the two different names came from (which you've dismissed as "noise") and rely on you (or me) to figure out _why_ they conflict.

You are _very welcome_ to improve the error messages if you think you can detect things better and express them to users better; that would take significant support burden off of me.
