### ISSUE TITLE
Error: New error

### ISSUE THREAD

**Issue by sagar-barapatre** [graphile/crystal#1896]
...

**Comment by benjie** [comment]
I’m not sure how this relates to Graphile Crystal?

**Comment by sagar-barapatre** [comment]
This isn't related to graphile, but I saw one issue created related to this error, The same error i am getting, I followed the same. But still getting the same error. Can you please help me out?

**Comment by benjie** [comment]
You need to find the position in your code that’s generating this issue and then look at the variables there and figure out why it’s happening. If you want help doing so you can [book a call with me](https://benjie.dev/book), I can’t do much to help otherwise.

Closing as completely unrelated to this project.
