### ISSUE TITLE
Stack traces are displayed in production and can't be disabled

### ISSUE THREAD

**Issue by apeschar** [graphile/crystal#1898]
Currently it seems that stack traces are always returned when they are available on the error object.

https://github.com/graphile/crystal/blob/main/grafast/grafserv/src/utils.ts#L48-L52

This may not be desirable because it leaks information about paths and code structure. I would propose disabling the stack traces when NODE_ENV is set to production.

I'm willing to submit a PR for this, but I'd like to have your opinion on whether checking only NODE_ENV is appropriate, or there should be a configuration option instead or in addition to a default depending on NODE_ENV.

![Screenshot 2023-12-26 at 18 44 34](https://github.com/graphile/crystal/assets/122977/f84e470a-5822-4d17-a727-7e97b0633ec5)

**Comment by benjie** [comment]
Use the preset.grafserv.maskError method to override how errors are escaped by default.

https://github.com/graphile/crystal/blob/1d75d727ac48a3ea34ab2a06c83b06b0a3e95cb3/grafast/grafserv/src/index.ts#L141

The error stack should never be included in a masked error so that definitely sounds like a bug in the default implementation. Fixing the bug would be welcome, no need for options.
