### ISSUE TITLE
(v5) I'd like get a generic executor from `build.input.pgRegistry` inside a `makeExtendSchemaPlugin`.

### ISSUE THREAD

**Issue by danneu** [graphile/crystal#2076]
I was directed here from Discord: https://discord.com/channels/489127045289476126/498852330754801666/1245437899022012607

### Summary

The docs show how to get an executor from a pgResource (where pgResources is simply going to be a list of exposed tables and functions in your postgres schema).

```typescript
export const ExamplePlugin = makeExtendSchemaPlugin((build) => {
  const { users } = build.input.pgRegistry.pgResources
  const { executor } = users
  return {
    plans: {
      Mutation: {
        example(_, fieldArgs) {
          const $input = fieldArgs.getRaw('input')
          const $result = withPgClientTransaction(
            executor,
            $input,
            async (pgClient, input) => {
              // ...
            }
          )
        }
      }
    }
  }
})
```

But it would be nice to be able to get a generic executor for the database instead of having to get one from specific tables, even if all of the executors for the same database actually are the same object.

**Comment by benjie** [comment]
I agree; pgRegistry should accept executors even before it accepts codecs; each executor should be named for itself; so you should be able to get `build.pgRegistry.pgExecutors.main` to get the main (default) executor, rather than having to extract it from a random resource knowing they all share the same executor.

This is very low priority, and I might not add it until after v5.0.0 goes live, so if anyone wants to work on it please do go ahead!
