### ISSUE TITLE
pgUnionAll.single() throws an error when the list is empty

### ISSUE THREAD

**Issue by achintha-weerasinghe** [graphile/crystal#2148]
### Summary

I have a union field which uses pgUnionAll in the plan. The field returns only one item, so I use `.single()` to get only item from the list returned from pgUnionAll.

### Steps to reproduce

1. Checkout [this branch](https://github.com/achintha-weerasinghe/ouch-my-finger/tree/bug/pg-union-single) from my forked repo of ouch-my-finger.
2. Create a database called `ouch_my_finger` and schema called `public`.
3. Use the db.sql to update the database with the tables and types.
4. Run `yarn dev` to start the dev server.
5. Try querying the `animalsById` with an invalid uuid.

### Expected results

Instead the error, null should be returned.

### Actual results

An error is thrown `TypeError: Cannot read properties of undefined (reading '0')`

**Comment by benjie** [comment]
In future, please try and keep your reproductions minimal to make it easier to track down what's important and what isn't. Here's what I extracted from your reproduction to reproduce the issue: https://github.com/benjie/ouch-my-finger/compare/main...achintha-minimal

**Comment by benjie** [comment]
This was an interesting one; turns out we hardly use `pgUnionAll` in the crystal codebase so it was severely under-tested. I've added another field to the example schema that uses pgUnionAll and have added a positive and negative test case for it along with the previous union type that was used. Thanks for the report!
