### ISSUE TITLE
Ruru: Websocket endpoint not followed?

### ISSUE THREAD

**Issue by tobiasBora** [graphile/crystal#2181]
### Summary

In ruru, typing:
```
$ npx ruru@beta -Pe http://localhost:5173/graphql  -S -s ws://localhost:4000/graphql
```
ends up in the websocket entry `ws://localhost:1337/graphql` being used (I can see this in an error message by firefox).

### Steps to reproduce

Just type the above command and try to subscribe to a graphql server.

### Expected results

I should use the port 4000.

### Actual results

It uses the port 1337

**Comment by benjie** [comment]
```
npx ruru@beta \
  -P # Proxy
  -e http://localhost:5173/graphql # This is your GraphQL endpoint
  -S # Enable subscriptions to ws://localhost:5173/graphql; except...
  -s ws://localhost:4000/graphql # Override websockets endpoint
```

Since you didn't supply `-p` we will run with the default port, 1337

So we will now proxy requests to `http://localhost:1337/graphql` to `http://localhost:5173/graphql` and requests to `ws://localhost:1337/graphql` will be proxied to `ws://localhost:4000/graphql`

> ends up in the websocket entry ws://localhost:1337/graphql being used (I can see this in an error message by firefox).

That seems correct: the URL that Ruru listens on (`localhost:1337`) should proxy to the websocket endpoint you've specified.

**Comment by tobiasBora** [comment]
Oh thanks, so this is how it works? But then I'm surprised that I got some errors about `ws://localhost:1337` being not reachable…

**Comment by benjie** [comment]
I assume you're making your request to http://localhost:1337? If so, it would seem extremely surprising that ws://localhost:1337 were not reachable since it literally uses the same HTTP connection and then upgrades it to websocket afterwards... Could you share screenshots of what you're seeing?
